name: Build LZ4 for Android
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install CMake
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.19.1/cmake-3.19.1-Linux-x86_64.sh
          chmod +x cmake-3.19.1-Linux-x86_64.sh
          ./cmake-3.19.1-Linux-x86_64.sh --skip-license --prefix=/usr/local
          echo "CMAKE_HOME=/usr/local" >> $GITHUB_ENV
      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip
          echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r26d" >> $GITHUB_ENV
      - name: Build LZ4 with Gradle
        run: |
          ./gradlew build -Pandroid.ndk.path=$ANDROID_NDK_HOME
      - name: Upload LZ4 binary
        uses: actions/upload-artifact@v4
        with:
          name: lz4-binary
          path: library/build/outputs/native/*/lz4
